# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10

    steps:
      - run: sudo mkdir -p /root/.npm/_cacache/tmp
      - run: npm install
      - run: sudo whoami
      - run: sudo ls -la /root
      - run: sudo ls -la /root/.npm
      - run: sudo ls -la /root/.npm/_cacache
      - run: sudo ls -la /root/.npm/_cacache/tmp
      - run: npm install npm install -g --unsafe-perm git://github.com/greenkeeperio/greenkeeper-lockfile#feat/monorepos
      - run: greenkeeper-lockfile-update
      - run: npm test
      - run: greenkeeper-lockfile-upload
