# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10

    steps:
      - run: mkdir ~/.npm-global
      - run: npm config set prefix '~/.npm-global'
      - run: export PATH=~/.npm-global/bin:$PATH
      - run: source ~/.bashrc
      - run: npm install
      - run: npm install -g git://github.com/greenkeeperio/greenkeeper-lockfile#feat/monorepos
      - run: /home/circleci/.npm-global/bin/greenkeeper-lockfile-update
      - run: npm test
      - run: /home/circleci/.npm-global/bin/greenkeeper-lockfile-upload
